# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages
warnings_are_errors: false

before_install:
  - tlmgr install index

addons:
  apt:
    packages:
      - libxml2-dev
      - libv8-dev
repos:
  CRAN: http://cran.rstudio.com
r_github_packages: okgreece/tableschema-r

after_success:
  - Rscript -e 'covr::codecov()'
