# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
pandoc_version: 1.19
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel  
before_install:
  - tlmgr install index
github_packages:
  - hadley/devtools
  - okgreece/tableschema.r
brew_packages:
 - jsonvalidate
 - V8
r_packages:
 - config
 - curl
 - future
 - httr
 - jsonlite
 - purrr
 - R6
 - R.utils
 - Rcpp
 - readr
 - roxygen2
 - stringr
 - tools
 - utils
addons:
  apt:
    packages:
      - libxml2-dev
warnings_are_errors: false